### PR TITLE
Fixed #7

### LINKED ISSUE #7: Uncaught JsonException: Malformed UTF-8 characters, possibly incorrectly encoded
```php
PHP Fatal error:  Uncaught JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in /var/www/html/dev/project/vendor/yiisoft/var-dumper/src/VarDumper.php:99
Stack trace:
#0 /var/www/html/dev/project/vendor/yiisoft/var-dumper/src/VarDumper.php(99): json_encode(Array, 4194304)
#1 /var/www/html/dev/project/vendor/yiisoft/yii-debug/src/Storage/FileStorage.php(68): Yiisoft\VarDumper\VarDumper->asJsonObjectsMap()
#2 /var/www/html/dev/project/vendor/yiisoft/yii-debug/src/Debugger.php(56): Yiisoft\Yii\Debug\Storage\FileStorage->flush()
#3 [internal function]: Yiisoft\Yii\Debug\Debugger->shutdown(Object(Yiisoft\Yii\Console\Event\ApplicationShutdown))
#4 /var/www/html/dev/project/vendor/yiisoft/injector/src/Injector.php(63): ReflectionFunction->invokeArgs(Array)
#5 /var/www/html/dev/project/vendor/yiisoft/yii-event/src/EventDispatcherProvider.php(75): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#6 /var/www/html/dev/project/vendor/yiisoft/event-dispatcher/src/Dispatcher/Dispatcher.php(28): Yiisoft\Yii\Even in /var/www/html/dev/project/vendor/yiisoft/var-dumper/src/VarDumper.php on line 99

Fatal error: Uncaught JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in /var/www/html/dev/project/vendor/yiisoft/var-dumper/src/VarDumper.php:99
Stack trace:
#0 /var/www/html/dev/project/vendor/yiisoft/var-dumper/src/VarDumper.php(99): json_encode(Array, 4194304)
#1 /var/www/html/dev/project/vendor/yiisoft/yii-debug/src/Storage/FileStorage.php(68): Yiisoft\VarDumper\VarDumper->asJsonObjectsMap()
#2 /var/www/html/dev/project/vendor/yiisoft/yii-debug/src/Debugger.php(56): Yiisoft\Yii\Debug\Storage\FileStorage->flush()
#3 [internal function]: Yiisoft\Yii\Debug\Debugger->shutdown(Object(Yiisoft\Yii\Console\Event\ApplicationShutdown))
#4 /var/www/html/dev/project/vendor/yiisoft/injector/src/Injector.php(63): ReflectionFunction->invokeArgs(Array)
#5 /var/www/html/dev/project/vendor/yiisoft/yii-event/src/EventDispatcherProvider.php(75): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#6 /var/www/html/dev/project/vendor/yiisoft/event-dispatcher/src/Dispatcher/Dispatcher.php(28): Yiisoft\Yii\Even in /var/www/html/dev/project/vendor/yiisoft/var-dumper/src/VarDumper.php on line 99
```

[dump.txt](https://github.com/yiisoft/var-dumper/files/5181841/dump.txt)

| Q                 | A
| ---------------- | ---
| PHP version      |  7.4.10

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | #7

### CODE REVIEW

File: src/VarDumper.php [hunk 1]
```diff
@@ -76,7 +76,7 @@ private function asArray(int $depth, int $objectCollapseLevel = 0): array
 
     public function asJson(int $depth = 50, bool $prettyPrint = false): string
     {
-        $options = JSON_THROW_ON_ERROR;
+        $options = JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_IGNORE;
```
Comment (samdark) [inline src/VarDumper.php:79]: Why not `JSON_INVALID_UTF8_SUBSTITUTE`?

**Review by hiqsol — APPROVED** [review]

**Review by samdark — APPROVED** [review]
